name: Go
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['BestSlices']
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: golangci/golangci-lint-action@v2
      with:
        working-directory: ${{matrix.module}}

    - name: Test
      run: go test ./...
      working-directory: ${{matrix.module}}